export type WorkProject = {
  title: string;
  slug: string;
  category: string;
  thumbnail: string | null;
  videoUrl: string | null;
  client: string;
  services: string;
  year: string;
};

export const creativeProjects: WorkProject[] = [
  {
    title: "Aviva",
    slug: "aviva",
    category: "",
    thumbnail: "/work/aviva.jpg",
    videoUrl: "https://vimeo.com/1189112084",
    client: "Aviva",
    services: "Creative | Post-Production",
    year: "2025",
  },
  {
    title: "West Cork Distillers",
    slug: "westcorkdistillers",
    category: "",
    thumbnail: "/work/westcorkdistillers.jpg",
    videoUrl: "https://www.youtube.com/watch?v=7qf7FcTK-lo",
    client: "West Cork Distillers",
    services: "Creative | Production | Post-Production",
    year: "2024",
  },
  {
    title: "Candido",
    slug: "candido",
    category: "",
    thumbnail: "/work/candido.jpg",
    videoUrl: "https://www.youtube.com/watch?v=nfSmv9zB7BA",
    client: "Candido",
    services: "Creative | Production | Post-Production",
    year: "2024",
  },
  {
    title: "Sport Ireland",
    slug: "sportireland",
    category: "",
    thumbnail: "/work/sportireland.jpg",
    videoUrl: "https://vimeo.com/913667078",
    client: "Sport Ireland",
    services: "Post-Production",
    year: "2024",
  },
  {
    title: "Her Sport",
    slug: "hersport",
    category: "",
    thumbnail: "/work/hersport.jpg",
    videoUrl: "https://www.youtube.com/watch?v=StR49EVlgQY",
    client: "Her Sport",
    services: "Production",
    year: "2024",
  },
  {
    title: "IOM",
    slug: "iom",
    category: "",
    thumbnail: "/work/iom.jpg",
    videoUrl: "https://www.youtube.com/watch?v=pwnZzV2R0J4",
    client: "IOM",
    services: "Post-Production",
    year: "2023",
  },
  {
    title: "Guinness",
    slug: "guinness",
    category: "",
    thumbnail: "/work/guinness.jpg",
    videoUrl: "https://www.youtube.com/watch?v=XlCog_WXZKk",
    client: "Guinness",
    services: "Post-Production",
    year: "2023",
  },
  {
    title: "Department of Justice",
    slug: "doj",
    category: "",
    thumbnail: "/work/doj.jpg",
    videoUrl: "https://www.youtube.com/watch?v=I7yQcyPWu8M",
    client: "DOJ",
    services: "Post-Production",
    year: "2023",
  },
  {
    title: "West Cork Distillers",
    slug: "wcd",
    category: "",
    thumbnail: "/work/wcd.jpg",
    videoUrl: "https://vimeo.com/913670742",
    client: "West Cork Distillers",
    services: "Creative | Production | Post-Production",
    year: "2023",
  },
  {
    title: "The Shoot",
    slug: "theshoot",
    category: "",
    thumbnail: "/work/theshoot.jpg",
    videoUrl: "https://www.youtube.com/watch?v=z8soUnuLjIY",
    client: "The Shoot",
    services: "Creative | Production | Post-Production",
    year: "2023",
  },
  {
    title: "IOM",
    slug: "iomireland",
    category: "",
    thumbnail: "/work/iomireland.jpg",
    videoUrl: "https://www.youtube.com/watch?v=QaubtNmdXQE",
    client: "IOM",
    services: "Post-Production",
    year: "2023",
  },
  {
    title: "Irish Cancer Society",
    slug: "irishcancersociety",
    category: "",
    thumbnail: "/work/ICS.png",
    videoUrl: "https://www.youtube.com/watch?v=zPEaZ1aej0c",
    client: "Irish Cancer Society",
    services: "Post-Production",
    year: "2022",
  },
];

export const corporateProjects: WorkProject[] = [
  {
    title: "Glenveagh",
    slug: "glenveagh",
    category: "Corporate",
    thumbnail: "/work/glenveagh.png",
    videoUrl: "https://www.youtube.com/watch?v=lkkabqHg2Ak&t",
    client: "Glenveagh",
    services: "Production | Post-Production",
    year: "2025",
  },
  {
    title: "Glenveagh",
    slug: "glenveagh-2",
    category: "Corporate",
    thumbnail: "/work/glenveagh-1.png",
    videoUrl: "https://www.youtube.com/watch?v=U5oTQq_60GM&t",
    client: "Glenveagh",
    services: "Production | Post-Production",
    year: "2024",
  },
  {
    title: "Common Purpose",
    slug: "commonpurpose",
    category: "Corporate",
    thumbnail: "/work/common-purpose.jpg",
    videoUrl: "https://www.youtube.com/watch?v=BmQQpckdAq8",
    client: "Common Purpose",
    services: "Production | Post-Production",
    year: "2025",
  },
  {
    title: "Common Purpose",
    slug: "commonpurpose-2",
    category: "Corporate",
    thumbnail: "/work/common-purpose-1.jpg",
    videoUrl: "https://vimeo.com/1197452572",
    client: "Common Purpose",
    services: "Production | Post-Production",
    year: "2025",
  },
  {
    title: "ELFC",
    slug: "elfc",
    category: "Corporate",
    thumbnail: "/work/elfc.png",
    videoUrl: "https://www.youtube.com/watch?v=MpgmzkL1MzI",
    client: "ELFC",
    services: "Production | Post-Production",
    year: "2024",
  },
  {
    title: "GORM",
    slug: "gorm",
    category: "Corporate",
    thumbnail: "/work/gorm.jpg",
    videoUrl: "https://www.youtube.com/watch?v=QrBUNRu_O6k",
    client: "GORM",
    services: "Production | Post-Production",
    year: "2024",
  },
];
